// Generated by CoffeeScript 1.6.2
var SparseDemo, global,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

global = typeof exports !== "undefined" && exports !== null ? exports : window;

if (!global.SparseDemo) {
  SparseDemo = global.SparseDemo = {};
}

(function($) {
  'use strict';
  var _ref;

  return SparseDemo.CollectionsView = (function(_super) {
    var _ref1;

    __extends(CollectionsView, _super);

    function CollectionsView() {
      _ref = CollectionsView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    CollectionsView.prototype.subviews = {
      'form': SparseDemo.CollectionsForm = (function(_super1) {
        var SparseClasses, _ref2;

        __extends(CollectionsForm, _super1);

        function CollectionsForm() {
          _ref1 = CollectionsForm.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        CollectionsForm.prototype.model = SparseClasses = (function(_super2) {
          __extends(SparseClasses, _super2);

          function SparseClasses() {
            _ref2 = SparseClasses.__super__.constructor.apply(this, arguments);
            return _ref2;
          }

          SparseClasses.prototype.model = SparseDemo.SparseClass;

          return SparseClasses;

        })(sparse.Collection);

        CollectionsForm.prototype.events = {
          'click #fetch_collection': function(evt) {
            var _this = this;

            return this.model.fetch({
              success: function(m, r, o) {
                return console.log("Parse API response: " + (JSON.strongify(r)));
              },
              error: function(m, r, o) {
                return console.log('failed to fetch collection');
              }
            });
          }
        };

        return CollectionsForm;

      })(SparseDemo.BaseView)
    };

    return CollectionsView;

  })(SparseDemo.BaseView);
})(jQuery);
