// Generated by CoffeeScript 1.6.2
var SparseDemo, global,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

global = typeof exports !== "undefined" && exports !== null ? exports : window;

if (!global.SparseDemo) {
  SparseDemo = global.SparseDemo = {};
}

(function($) {
  'use strict';
  var _ref;

  return SparseDemo.UserView = (function(_super) {
    var _ref1;

    __extends(UserView, _super);

    function UserView() {
      _ref = UserView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    UserView.prototype.subviews = {
      'form': SparseDemo.UserForm = (function(_super1) {
        __extends(UserForm, _super1);

        function UserForm() {
          _ref1 = UserForm.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        UserForm.prototype.model = new sparse.User({
          username: "a.user",
          password: "sParse"
        });

        UserForm.prototype.init = function(o) {
          return rivets.bind(this.el, {
            user: this.model
          });
        };

        UserForm.prototype.events = {
          'click #create_user': function(evt) {
            var _this = this;

            return this.model.save(null, {
              success: function(m, r, o) {
                $(evt.target).attr('disabled', true).siblings().attr('disabled', false);
                return console.log("Parse API response: " + (JSON.stringify(r)));
              },
              error: function(m, r, o) {
                return console.log('failed to create user');
              }
            });
          },
          'click #login_user': function(evt) {
            var _this = this;

            evt.preventDefault();
            this.model.login({
              success: function(m, r, o) {
                return console.log("Parse API response: " + (JSON.strongify(r)));
              },
              error: function(m, r, o) {
                return console.log('failed to login user');
              }
            });
            return false;
          },
          'click #logout_user': function(evt) {
            var _this = this;

            evt.preventDefault();
            this.model.logout({
              success: function(m, r, o) {
                return console.log("Parse API response: " + (JSON.strongify(r)));
              },
              error: function(m, r, o) {
                return console.log('failed to logout user');
              }
            });
            return false;
          },
          'click #destroy_user': function(evt) {
            var _this = this;

            evt.preventDefault();
            this.model.destroy({
              success: function(m, r, o) {
                return console.log("Parse API response: " + (JSON.strongify(r)));
              },
              error: function(m, r, o) {
                return console.log('failed to destroy user');
              }
            });
            return false;
          }
        };

        return UserForm;

      })(SparseDemo.APIFormView)
    };

    return UserView;

  })(SparseDemo.BaseView);
})(jQuery);
