// Generated by CoffeeScript 1.10.0
var SparseDemo, global,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

global = typeof exports !== "undefined" && exports !== null ? exports : window;

if (!global.SparseDemo) {
  SparseDemo = global.SparseDemo = {};
}

(function($) {
  'use strict';
  return SparseDemo.UserView = (function(superClass) {
    extend(UserView, superClass);

    function UserView() {
      return UserView.__super__.constructor.apply(this, arguments);
    }

    UserView.prototype.reset = function() {
      if (!this['form'].model.isNew()) {
        if (!sparse.SESSION_TOKEN) {
          return this['form'].model.login(this['form'].model.get('username'), this['form'].model.get('password'), {
            success: (function(_this) {
              return function(m, r, o) {
                return _this.reset();
              };
            })(this)
          });
        } else {
          return this['form'].model.destroy({
            success: (function(_this) {
              return function() {
                _this['form'].model.clear();
                _this['form'].model.set(_this['form'].__defaults);
                return _this['form'].$el.find('#create_user').attr('disabled', false).siblings().attr('disabled', true);
              };
            })(this)
          });
        }
      }
    };

    UserView.prototype.subviews = {
      'form': SparseDemo.UserForm = (function(superClass1) {
        extend(UserForm, superClass1);

        function UserForm() {
          return UserForm.__super__.constructor.apply(this, arguments);
        }

        UserForm.prototype.__defaults = {
          username: "a.user",
          password: "sParse"
        };

        UserForm.prototype.model = new sparse.User({
          username: "a.user",
          password: "sParse"
        });

        UserForm.prototype.init = function(o) {
          return rivets.bind(this.el, {
            user: this.model
          });
        };

        UserForm.prototype.events = {
          'click #create_user': function(evt) {
            return this.model.save(null, {
              success: (function(_this) {
                return function(m, r, o) {
                  $(evt.target).attr('disabled', true);
                  return _this.$el.find('#login_user').attr('disabled', false);
                };
              })(this),
              error: function(m, r, o) {
                return console.log('failed to create user');
              }
            });
          },
          'click #login_user': function(evt) {
            evt.preventDefault();
            this.model.login(this.model.get('username'), this.model.get('password'), {
              success: (function(_this) {
                return function(m, r, o) {
                  $(evt.target).attr('disabled', true);
                  _this.$el.find('#logout_user').attr('disabled', false);
                  return _this.$el.find('#destroy_user').attr('disabled', false);
                };
              })(this),
              error: function(m, r, o) {
                return console.log('failed to login user');
              }
            });
            return false;
          },
          'click #logout_user': function(evt) {
            evt.preventDefault();
            this.model.logout();
            this.$el.find('#login_user').attr('disabled', false).siblings().attr('disabled', true);
            return false;
          },
          'click #destroy_user': function(evt) {
            evt.preventDefault();
            this.__parent.reset();
            return false;
          }
        };

        return UserForm;

      })(SparseDemo.APIFormView)
    };

    return UserView;

  })(SparseDemo.BaseView);
})(jQuery);
